# Generated by Django 5.0.6 on 2024-05-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('most valuable', 'Most Valuable'), ('valuable', 'Valuable'), ('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=20),
        ),
    ]
